name: Olá Mundo

on: [ push, workflow_dispatch ]

jobs:
  entrega_aws:
    runs-on: ubuntu-latest

    environment:
      name: devl

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ID_CHAVE_AWS }}
          aws-secret-access-key: ${{ secrets.SEGREDO_CHAVE_AWS }}
          aws-region: us-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Validar Terraform
        working-directory: terraform
        run: terraform validate

      - name: Planejamento Terraform
        working-directory: terraform
        run: terraform plan -out=tfplan

      - name: Aplicar Terraform
        working-directory: terraform
        run: terraform apply -auto-approve tfplan
  