name: Olá Mundo

on: [ push, workflow_dispatch ]

jobs:
  preparar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy to build directory
        run: |
          mkdir -p build
          cp -r src/* build/

      - name: Configurar zip
        run: sudo apt-get install zip -y

      - name: Comprimir arquivos
        working-directory: build
        run: |
          zip -r impacta.zip *

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: impacta-lambda
          path: build/impacta.zip

  entrega_aws:
    needs: preparar
    runs-on: ubuntu-latest

    environment:
      name: devl

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: impacta-lambda
          path: build

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ID_CHAVE_AWS }}
          aws-secret-access-key: ${{ secrets.SEGREDO_CHAVE_AWS }}
          aws-region: us-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Inicializar Terraform
        working-directory: terraform
        run: terraform init -input=false

      - name: Validar Terraform
        working-directory: terraform
        run: terraform validate

      - name: Planejamento Terraform
        working-directory: terraform
        run: terraform plan -out=tfplan

      - name: Aplicar Terraform
        working-directory: terraform
        env:
          TF_VAR_mensagem_personalizada: ${{ vars.NOME_DO_AMBIENTE }}
        run: terraform apply -auto-approve tfplan
  