name: Deploy da nossa aplicação na AWS

on: [ push ]

jobs:
  
  entrega:
    runs-on: ubuntu-latest

    steps:
      - name: sincronizar repo
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
         terraform_version: "1.5.6"

      - name: Autenticar na AWS
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-access-key-id: ${{ secrets.ID_CHAVE_AWS }}
          aws-secret-access-key: ${{ secrets.SEGREDO_CHAVE_AWS}}
          aws-region: us-east-1

      - name: Inicializar Terraform
        working-directory: terraform
        run: terraform init -input=false

      - name: Validar Terraform
        working-directory: terraform
        run: terraform validate

      - name: Planejamento Terraform
        working-directory: terraform
        run: terraform plan -out=tfplan

      - name: Aplicar Terraform
        working-directory: terraform
        run: terraform apply -auto-approve tfplan