name: Olá Mundo

on: [ push, workflow_dispatch ]

jobs:
  ola:
    runs-on: ubuntu-latest

    steps:
      - name: Dizer ola
        run: echo Olá Impacta ! "

      - name: Ver arquivos
        run: ls -la

      - name: Atualizar Repositório
        uses: actions/checkout@v4

      - name: Ver arquivos
        run: ls -la
  
  ola-novamente:
    runs-on: ubuntu-latest

    needs: ["ola"]

    steps:
      - name: Ola Novamente 
        run: echo "Ola Novamente"