name: Deploy da nossa aplicação na AWS

on: [ push ]

jobs:

  testar:
    runs-on: ubuntu-latest
    outputs:
      cobertura: ${{ steps.executar_testes.outputs.cobertura }}

    steps:
    - name: sincronizar repo
      uses: actions/checkout@v4

    - name: configurar node
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    
    - name: instalar dependências
      run: npm ci

    - name: executar testes com cobertura
      id: executar_testes
      run: |
        npm test -- --coverage --coverageReporters=json-summary || true
        
        COBERTURA=$(node -p "JSON.parse(require('fs').readFileSync('coverage/coverage-summary.json')).total.lines.pct")

        echo "cobertura=${COBERTURA}" >> $GITHUB_OUTPUT
        echo "Cobertura de código: ${COBERTURA}%"

  resumir_cobertura:
    name: resumir cobertura
    runs-on: ubuntu-latest
    needs: testar
    steps:
    - name: escrever resumo no job summary
      run: |
        echo "## Cobertura de Código" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Cobertura:** ${{ needs.testar.outputs.cobertura }}%" >> $GITHUB_STEP_SUMMARY