name: Olá Mundo

on: push

jobs:
  ola:
    runs-on: ubuntu-latest
    env:
      MINHA_OUTRA_VAR: "outra coisa"
    steps:
      - name: Dizer ola
        run: echo " Olá Impacta a minha variável do repositório é ${{ vars.MINHA_VAR }}"

      - name: Dizer outra coisa
        run: echo "Agora estou $MINHA_OUTRA_VAR"

      - name: Dizer um segredo
        run: echo "O meu segredo é ${{secrets.MEU_SEGREDO}}"

      - name: Dizer um segredo por meio de uma variável de ambiente
        env:
          SEGREDO: ${{secrets.MEU_SEGREDO}}
        run: echo "O meu segredo é $SEGREDO"
  