name: Olá Mundo

on: [ push, workflow_dispatch ]

jobs:
  config:
    runs-on: ubuntu-latest
    
    outputs:
      info: ${{steps.add_info.outputs.VAR_INFO}}

    steps:
      - name: Adicionar info
        id: add_info
        run: echo "VAR_INFO=impacta" >> $GITHUB_OUTPUT

  relat:
    runs-on: ubuntu-latest

    needs: config

    steps:
      - name: Usar info
        run: echo "A info diz ${{needs.config.outputs.info}}"