name: Olá Mundo

on: [ push, workflow_dispatch ]

jobs:
  ola:
    runs-on: ubuntu-latest

    env:
      MINHA_OUTRA_VAR: "outra coisa"
    steps:
      - name: Dizer ola
        id: dizer_ola
        run: echo "VAR_INFO=importante" >> $GITHUB_OUTPUT

      - name: Dizer um segredo
        run: echo "a var diz ${{steps.dizer_ola.outputs.VAR_INFO}}"