name: Olá Mundo

on: push

jobs:
  ola:
    runs-on: ubuntu-latest
    environment:
      name: desenvolvimento
    steps:
      - name: Dizer ola
        run: echo " Olá Impacta a minha variável do repositório é ${{ vars.MINHA_VAR }}"

      - name: Usar variável de ambiente
        run: echo "Olá, ${{ env.MINHA_VAR_DE_AMBIENTE }}"
  