name: Enviar aplicação para nuvem

on: push

env:
  WORKFLOW: "Nivel do workflow"

jobs:
  algo:
    runs-on: ubuntu-latest

    env:
      JOB: "Nivel do job" 

    steps:
      - name: Algo importante
        env: 
          STEP: "nivel do step"
        run: | 
          echo "$WORKFLOW"
          echo "$JOB"
          echo "$STEP"

      - name: Algo n funciona
        run: | 
          echo "$STEP"
          echo "$JOB"