name: Enviar aplicação para nuvem

on: push

jobs:
  algo:
    runs-on: ubuntu-latest

    steps:
      - name: Algo importante
        env: 
          SEGREDO: ${{secrets.CHAVE_DE_ACESSO_AO_SERVIDOR}}
          NSEGREDO: ${{vars.MINHA_VAR}}
        run: | 
          echo "A coisa confidencial é ${{ secrets.CHAVE_DE_ACESSO_AO_SERVIDOR }}"
          echo "Algo que não existe ${{ secrets.CHAVE_DE_ACESSO}}"
          echo "$SEGREDO"
          echo "$NSEGREDO"